/*
 * Jakefile
 * capp
 *
 * Created by You on February 18, 2010.
 * Copyright 2010, Your Company All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    task = require("jake").task,
    FileList = require("jake").FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("capp", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "capp.build", configuration));
    task.setBuildPath(FILE.join("Build"));

    task.setProductName("yogo_app");
    task.setIdentifier("edu.montana.cns.yogo");
    task.setVersion("1.0");
    task.setAuthor("Yogo Group");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("yogo_app");
    task.setSources(new FileList("**/*.j"));
    task.setResources(new FileList("Resources/*"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");
    task.setNib2CibFlags("-R Resources/");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["capp"]);
